# Generated by Django 2.2.5 on 2019-09-14 06:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.IntegerField(null=True)),
                ('plan_gross', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Employee')),
            ],
            bases=('users.employee',),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)])),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leg', to='users.Dispatcher')),
                ('senior_dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senior', to='users.Dispatcher')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Employee')),
                ('monitor_dispatcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor', to='users.Dispatcher')),
            ],
            bases=('users.employee',),
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='legs',
            field=models.ManyToManyField(through='users.Relationship', to='users.Dispatcher'),
        ),
    ]
