# Generated by Django 2.2.5 on 2019-09-14 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='reward_percentage',
            field=models.FloatField(default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='reward_percentage',
            field=models.FloatField(default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
